# Generated by Django 4.2 on 2025-01-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Cultural', 'Cultural'), ('Sports', 'Sports'), ('Social', 'Social'), ('Economic', 'Economic'), ('Political', 'Political'), ('Scientific', 'Scientific'), ('Artistic', 'Artistic')], max_length=100, unique=True),
        ),
    ]
